{% set version = '3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hunspell
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/hunspell_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/hunspell/hunspell_{{ version }}.tar.gz
  sha256: 01fb9c87f7cf094aaad3b7098378134f2e503286224351e91d08c00b6ee19857

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: spelling, testthat, pdftools, janeaustenr, wordcloud2, knitr, stopwords, rmarkdown
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp
    - r-digest

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-digest

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('hunspell')"           # [not win]
    - "\"%R%\" -e \"library('hunspell')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/ropensci/hunspell#readme (devel) https://hunspell.github.io (upstream)
  license: GPL-2 | LGPL-2.1 | MPL-1.1
  summary: Low level spell checker and morphological analyzer based on the  famous 'hunspell'
    library <https://hunspell.github.io>. The package can analyze or check individual
    words as well as parse text, latex, html or xml documents. For a more user-friendly
    interface use the 'spelling' package which builds on this package to automate checking
    of files, documentation and vignettes in all common formats.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: hunspell
# Type: Package
# Title: High-Performance Stemmer, Tokenizer, and Spell Checker
# Version: 3.0
# Depends: R (>= 3.0.2)
# Encoding: UTF-8
# Authors@R: c( person("Jeroen", "Ooms", ,"jeroen@berkeley.edu", role = c("aut", "cre")), person("Authors of libhunspell", role = "cph", comment = "see AUTHORS file"))
# Description: Low level spell checker and morphological analyzer based on the  famous 'hunspell' library <https://hunspell.github.io>. The package can analyze or check individual words as well as parse text, latex, html or xml documents. For a more user-friendly interface use the 'spelling' package which builds on this package to automate checking of files, documentation and vignettes in all common formats.
# License: GPL-2 | LGPL-2.1 | MPL-1.1
# URL: https://github.com/ropensci/hunspell#readme (devel) https://hunspell.github.io (upstream)
# BugReports: https://github.com/ropensci/hunspell/issues
# Imports: Rcpp, digest
# LinkingTo: Rcpp (>= 0.12.12)
# Suggests: spelling, testthat, pdftools, janeaustenr, wordcloud2, knitr, stopwords, rmarkdown
# VignetteBuilder: knitr
# RoxygenNote: 6.1.1
# Language: en-US
# NeedsCompilation: yes
# Packaged: 2018-12-15 15:40:04 UTC; jeroen
# Author: Jeroen Ooms [aut, cre], Authors of libhunspell [cph] (see AUTHORS file)
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2018-12-15 16:20:03 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
