travis:
  secure:
    BINSTAR_TOKEN: 4Qo8to/UJEeYWCOzIc67AMhDUAlMG990Gb4ujXHupGrm4/UVI8Jj1N4jQNFvYrfJ6csZWmTu7FhdbHqtbPppIeY0kJwZIDUe0VI71wevKQ4EuyUWH4eTeOcrh/ep1sJbpRsxbA9XPIBgTyTl7SIE8cOT6EfWHcIq9okX7BAUECUx6Po/IzkhVxUn/5yXGh0kYvIIxmqDR84m1gdYijSpzww3qYQmjAf4SN+vgtNq6KozhXMxzLvg4+1ddlqsXbgjx9j9aM6cKFbryD4SLwerWt/oehWw+CCTLgy2dpgt6VGNeL0OLa+yWLup7/vzTYtfuBpC6Ae+2eInE6glhrAp8nbKq9ygAi5z+uivNM4p6T9vllJEM8BDuSxGBQSMEtJxQaSrI5cgxxC+xDRjpacIMHhqAzdC4HjCXzic3L+TapF+FtCjaY1/f6xth+MkUIoZR4T2eOP+CHseBYniqh0MuP8ZBFsRlif/4Ar80pWJcCq2PYJC2NxlzOyTEV9gxXwij/sRIlhBOltFAhDhe8kTUUXdFJgrQCYI56pdLoq477FJE4QXgp9OtdP2iiR+Kt+rOcbL+6b4QzsbeXmKzaTkCW8ZQv6xAdrIzWc9Mu66iiOMUsH4aKhMWmqt+QgUWeADEAoXFg12ZJUhL6jnSbQClMa3xxip2ZbU+r3EMgF91qU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
