travis:
  secure:
    BINSTAR_TOKEN: ubhgw6hutELyvxWuCmWPR/XB9AIr1vNVeKdy6aVVIO0W0uRizuK1/WUN/EKX+WUrBzggLxrz+RwGvu3Um9K18RN3XvIj6Aft4rBR1AKBao/WhL4eAq8U3TOiv3P7keiNv+APhgBamNuTWnYmcZdbiPlrobyfBBxnPCtD7iUK3vj9/eW84Cs/8Z1dcGPxtlk7+WP5Ox0RMiHHCh/T/og6TXtFcb74CHP4pp/AMuAR+Q2F/oJUVlYmeU3sVOuyF7WidoSkBOfGGPGOurFWYUNrrt72pH32vQYuvuu6zpQFI5b8Y+r8olWBXqlNjxNp58Qb01XFBpb5BdZJNPCLAD6CJ0N5RD9IVx23HDgJ7Mou4didH+AniwQNv8cTyZF9joUiL+1C0Yen4g3vRsJ7BputRbSdCOxrNTdRH1727khYL6xFN68OiFOhPj4Cq6sS+dUIkK13B71w/jByORzQrRaHfD+Lg8kWh4If+s7XaqZ/Ckk9n+p8kCOUjVQh1M++yp190VkaHX163FTQKIG+S5iZQLZRlc8Xe7iiActqoocpxUvAlw46F0i8TW9tbNSKIFC2EeVUllZTztuyAqvGNxkPgP1rtJuo4tZSX6zSZ68yVbziJA7tcARd8MvFRkXc1Ota0swaynnRoAvHjFJCyF61tImklGfhcfxbGTiRjcPBBao=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
